# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_TOKEN  }}

      - name: Get Short SHA
        id: vars
        run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./WebApplication
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hqv1/dominoes-api:${{ steps.vars.outputs.sha_short }}
  
      - name: Set K8s context
        id: setcontext
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}            

      - name: Variable Substitution in K8s Deployment file
        uses: danielr1996/envsubst-action@1.0.0
        env:
            ASPNETCORE_ENVIRONMENT: Staging
        with:
          input: ./WebApplication/config/deployment.yml
          output: ./WebApplication/config/deployment_updated.yml      

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'dominoes'
          manifests: ./WebApplication/config/deployment_updated.yml # Uses the output from Variable Substitution in K8s Deployment file
          images: 'hqv1/dominoes-api:${{ steps.vars.outputs.sha_short }}'          
          kubectl-version: 'latest'
